In [2]:
import numpy as np
A = np.arange(12).reshape(3,-1)
A1 = A[:,1]
print('A =',A)
print('A1 =',A1)
print('A1 dimension =',A1.shape)
B = np.arange(16).reshape(4,-1)
B1 = B[0,:]
print('B =', B)
print('B1 =', B1)
print('B1 dimension =',B1.shape)
# C = np.dot(A1,B1)
# print(C)
C = np.dot(A1.reshape(3,1),B1.reshape(1,4))
print("inner product of A1 and B1: ", C)
np.transpose(A)

A = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A1 = [1 5 9]
A1 dimension = (3,)
B = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
B1 = [0 1 2 3]
B1 dimension = (4,)
inner product of A1 and B1:  [[ 0  1  2  3]
 [ 0  5 10 15]
 [ 0  9 18 27]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])